name: Build and Release [Linux]
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compilation
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: classes
      - name: Unit tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
      - name: Integration tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: integrationTest
      - name: Functional tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: functionalTest
      - name: Assemble artifact
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
      - name: Store artifact
        uses: actions/upload-artifact@v2
        with:
          name: gradle-tomcat-plugin.jar
          path: build/libs/*.jar
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: bmuschko
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          MAVEN_CENTRAL_USER_TOKEN: ${{ secrets.MAVEN_CENTRAL_USER_TOKEN }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with:
          arguments: bintrayUpload gitPublishPush -Dorg.ajoberstar.grgit.auth.username=${{ secrets.GH_TOKEN }} -is